DEV-20
KirillSachkov/sachkov-tech pull request #13
Opened 2024-10-05 10:37 UTC by aznoran

2024-10-05 10:40 UTC, aznoran commented
![image](https://github.com/user-attachments/assets/7f246b9a-f181-4dea-9ff2-fecb3e0f860b)
пока что такие ссылки

2024-10-05 17:22 UTC, KirillSachkov requested changes
Всё отлично, нужно только одно исправлен

2024-10-05 17:22 UTC, KirillSachkov commented on backend/src/IssuesReviews/SachkovTech.IssuesReviews.Presentation/IssuesReviews/IssuesReviewsController.cs
> +    public async Task<ActionResult> GetAll(
не getAll, а GetByIssueReviewId

2024-10-05 17:22 UTC, KirillSachkov commented on backend/src/IssuesReviews/SachkovTech.IssuesReviews.Presentation/IssuesReviews/Requests/AddCommentRequest.cs
> +}
Реквесты и ответы теперь нужно класть в проекст Contracts, поэтому метод ToCommand нужно убрать, так как у нас не будет ссылки на application слой

2024-10-05 17:22 UTC, KirillSachkov commented on backend/src/IssuesReviews/SachkovTech.IssuesReviews.Presentation/IssuesReviews/IssuesReviewsController.cs
> +    public async Task<ActionResult> Create(
Не Create, а Comment - комментировать. + изменить роут на {id:guid/comment}

2024-10-05 17:22 UTC, KirillSachkov commented on backend/src/IssuesReviews/SachkovTech.IssuesReviews.Presentation/IssuesReviews/IssuesReviewsController.cs
> +    public async Task<ActionResult> GetAll(
изменить роут на (/id:guid/comments)

2024-10-06 13:59 UTC, aznoran commented
![image](https://github.com/user-attachments/assets/240d0df9-a559-43a5-b1d0-30305a0bf2ab)

я не лез в не свой контекст но спешу предупредить что solution folder и настоящая папка в названиях отличаются. В моем контексте та же проблема была и я переименовал solution folder

2024-10-06 14:25 UTC, KirillSachkov approved these changes
Всё ок, папку потом переименуем, не забудь решить конфликты и можешь мержить

2024-10-06 15:10 UTC, merged