DEV-24
KirillSachkov/sachkov-tech pull request #20
Opened 2024-10-10 16:54 UTC by aznoran

2024-10-10 16:55 UTC, aznoran commented
всё также нет реализации Infrastructure для IssuesReviews, поэтому проверить не могу, прошел мысленно по методам. Не легко

2024-10-10 17:03 UTC, aznoran commented
Еще вопрос на счёт роутов в IssueSolvingController, нормальные они или если нет, то как лучше?

2024-10-11 08:54 UTC, KirillSachkov approved these changes

2024-10-11 08:54 UTC, KirillSachkov commented on backend/src/IssueSolvings/SachkovTech.IssueSolving.Presentation/IssueSolvingController.cs
> +    [HttpPut("{userIssueId:guid}")]
давай сделаем post, потому что мы создаем новый ресурс - issue review. + поменяем роут на "userIssueId:guid/review

2024-10-11 08:54 UTC, KirillSachkov commented on backend/src/IssueSolvings/SachkovTech.IssueSolving.Presentation/IssueSolvingController.cs
> +        var command = new SendOnReviewCommand(userIssueId,Guid.Parse(userId), request.PullRequestUrl);
нет пробелов в параметрах

2024-10-11 08:58 UTC, KirillSachkov requested changes
исправления

2024-10-11 19:21 UTC, aznoran commented
Много коммитов из-за rebase , по факту смотреть нужно только последний fix

А теперь комментарии:

1)Добавил каждому свой IUnitOfWork и зарегал Scoped

2)Пришлось убрать ParentId у IssueDto и сделать LessonId nullable - видимо логика поменялась у Issues и пока это не исправили. Я закомментил но если надо то удалю полностью

3)Пришлось добавить метод PullRequestEmpty - ef ругается что complexproperty can't be null, поэтому я сделал ссылку ""

4)Когда я делал проверку - я не использовал аутентификацию и захардкодил UserId , ибо были ошибки с AdminOptions

2024-10-11 20:24 UTC, aznoran commented
1) IssueStatus.NotCompleted никогда не будет у UserIssue с нынешней реализацией 
![image](https://github.com/user-attachments/assets/d2b342eb-2139-4de7-89d2-56cbc92d1cbd)
![image](https://github.com/user-attachments/assets/becf1e22-f71d-4b6b-8493-6c7e37378dbb)
![image](https://github.com/user-attachments/assets/03efb0f5-55f7-4c15-bf72-f4ab6db5c28e)

2) я решил задачу "Кирилл заметил еще одну вещь, при взятии задачу на работу нет проверки, была ли взята эта задача до этого и я могу сделать вот такие вещи. Исправить так, чтобы нельзя было взять одну и ту же задачу в работу несколько раз ?" следующим образом - я проверяю, что userissue для issue уже существует и если да - ошибка. Потому что статусы "задача не не была в работе или требуется доработкаv" это статус IssueReview а не IssueSolving поэтому я думаю нужен отдельный эндпоинт, а в этом просто запретить создание больше чем модной UserIssue

2024-10-13 11:07 UTC, KirillSachkov requested changes
Да, давай из UserIssue уберём ненужный статус, потому что нерешенная задача это по сути задача, которая общая, он ещё не взял её в работу, поэтому такого статуса у UserIssue и не может быть.

2024-10-13 11:07 UTC, KirillSachkov commented on backend/src/Shared/SachkovTech.SharedKernel/ValueObjects/PullRequestUrl.cs
> +    }
Лучше сделать это не методом, а статическим readonly полем

2024-10-13 14:24 UTC, merged