Interceptor, BG service for delete issues
KirillSachkov/sachkov-tech pull request #21
Opened 2024-10-11 11:02 UTC by DanC-rep

1. Added soft delete by interceptor
2. Added background service for issues with expired deletion date
3. Added feature to restore issue
4. Added uow for each module

2024-10-11 16:42 UTC, KirillSachkov requested changes

2024-10-11 16:42 UTC, KirillSachkov commented on backend/src/Issues/SachkovTech.Issues.Infrastructure/BackgroundServices/DeleteExpiredIssuesBackgroundService.cs
> +        await Task.Delay(
здесь нет смысла вызывать ожидание, можно просто в конце цикла оставить delay

2024-10-11 16:42 UTC, KirillSachkov commented on backend/src/Issues/SachkovTech.Issues.Infrastructure/Constants.cs
> +    public const int LIFETIME_AFTER_DELETION = -30;
не нужно указывать здесь -, становится непонятно, просто 30

2024-10-11 16:46 UTC, KirillSachkov commented
> Реализовал весь указанный функционал, но тут у меня возникло 2 проблемы:
> 
> 1. Теперь метод ForceDelete у Issue поломался из-за того, что там все теперь происходит по тому же принципу, что и в soft. Хотел узнать, как лучше сделать
> 2. Тут проблема с BG сервисом. Он в целом работает, удаляет задачи по истечении срока, но при тестировании я удалял задачи через SoftDelete, после чего в сервисе по удалению файлов можно было увидеть, что isDeleted установилась в false, а DeletionDate устанавливается в null, хотя в бд он хранит все верные значения полей. После перезагрузки приложения поля снова содержат верные значения. Вот здесь я запутался, поскольку ошибок в логике работы я найти не смог. Надеюсь у тебя есть мысли по этому поводу
>    ![1](https://private-user-images.githubusercontent.com/74724331/375732726-646f5c5d-7290-45b2-8ab0-bf9d2a0b3980.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NjUyNzQsIm5iZiI6MTcyODY2NDk3NCwicGF0aCI6Ii83NDcyNDMzMS8zNzU3MzI3MjYtNjQ2ZjVjNWQtNzI5MC00NWIyLThhYjAtYmY5ZDJhMGIzOTgwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDE2NDI1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyZTM0MGFkYmU0OWJkNDdiN2FiNjg1YmViN2M5YWJhYjUwOTVmMTQ4ZjI1NzdiYzllMTAzMWUwODNjZmIxOGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7lTQXH09opI2LJ1U1ua36CYhvkwZicETblUJFIMUEBw)

давай избавимся от интерсептора, а то слишком много логики на нём завязывается. будем получается удалять issue через модуль, когда soft delete, то не нужно задачу убирать из коллекции, просто устанавливать как удалённое. А если удаляем уже полностью, то тогда нужно удалить из коллекции и полностью стереть запись из бд. И давай добавим метод в модуль DeleteExpiredIssues или типа того, который сам будет исказать протукшие задачи и удалять их, этот метод будет вызывать db сервис

2024-10-11 21:13 UTC, DanC-rep commented
В общем я перенес логику поиска и удаления протухших задач в module, но проблема осталась аналогичной - у некоторых задач значения полей в бд и в коде расходятся

2024-10-13 16:39 UTC, KirillSachkov approved these changes

2024-10-13 16:59 UTC, merged