Gasanaliev/DEV-23
KirillSachkov/sachkov-tech pull request #25
Opened 2024-10-14 17:54 UTC by Perbudag

2024-10-14 19:10 UTC, KirillSachkov requested changes

2024-10-14 19:10 UTC, KirillSachkov commented on .vs/VSWorkspaceState.json
> +{
этого файла быть не должно

2024-10-14 19:10 UTC, KirillSachkov commented on .vs/sachkov-tech/v17/DocumentLayout.json
> +  "Version": 1,
этого файла тоже не должно быть

2024-10-14 19:10 UTC, KirillSachkov commented on backend/src/Files/SachkovTech.Files.Contracts/Dtos/GetLinkFileResult.cs
> +    public record GetLinkFileResult(FilePath FilePath, string Link);
здесь не нужно возврвщать FilePath, тем более это VO, который нельзя возвращать в респонсе. Нужно вернуть List<FileLinkDto>, где FileLinkDto это Id файла + ссылка на скачивание файла.

2024-10-14 19:10 UTC, KirillSachkov commented on backend/src/Files/SachkovTech.Files.Application/Queries/GetLinkFiles/GetLinkFilesHandler.cs
> +
пустой отступ

2024-10-14 19:10 UTC, KirillSachkov commented on backend/src/Files/SachkovTech.Files.Infrastructure/Database/FilesReadDbContext.cs
> +            modelBuilder.Entity<IssueDto>().HasQueryFilter(i => !i.IsDeleted);
здесь это не нужно

2024-10-14 19:10 UTC, KirillSachkov commented on backend/src/Files/SachkovTech.Files.Infrastructure/Providers/MinioProvider.cs
> +            cancellationToken);
если бакета нет, то можно сразу возвращать пустой результат

2024-10-14 19:10 UTC, KirillSachkov commented on backend/src/Files/SachkovTech.Files.Domain/ValueObjects/FilePath.cs
> +    public string Prefix => GetPrefix();
Не совсем понимаю за что у файла отвечает prefix

2024-10-15 06:14 UTC, Perbudag commented on backend/src/Files/SachkovTech.Files.Contracts/Dtos/GetLinkFileResult.cs
> +    public record GetLinkFileResult(FilePath FilePath, string Link);
GetLinkFileResult не используется вне модуля Files. Я думаю его лучше перенести в слой application.

2024-10-15 06:14 UTC, Perbudag commented on backend/src/Files/SachkovTech.Files.Application/Queries/GetLinkFiles/GetLinkFilesHandler.cs
> +
Исправлю

2024-10-15 06:15 UTC, Perbudag commented on backend/src/Files/SachkovTech.Files.Infrastructure/Database/FilesReadDbContext.cs
> +            modelBuilder.Entity<IssueDto>().HasQueryFilter(i => !i.IsDeleted);
Исправлю

2024-10-15 06:15 UTC, Perbudag commented on backend/src/Files/SachkovTech.Files.Infrastructure/Providers/MinioProvider.cs
> +            cancellationToken);
Исправлю

2024-10-15 06:23 UTC, Perbudag commented on backend/src/Files/SachkovTech.Files.Domain/ValueObjects/FilePath.cs
> +    public string Prefix => GetPrefix();
Я сделал так, чтобы в базе данных хранился полный путь к файлу в файловом хранилище (Начиная с названия корзины и заканчивая названием файла). Выглядит это так: 
BucketName/Prefix/FileName.
Префикс это папки внутри корзины в Minio. 
В будущем мы будем сортировать файлы по папкам, в зависимости от их mime типов.
Выглядеть это будет так: 
issues(корзина)/images(префикс, папка, в которой хранятся картинки)/asdasdasdasdsgsdg.jpeg(файл картинки).

2024-10-15 06:23 UTC, Perbudag commented on .vs/VSWorkspaceState.json
> +{
Удалю

2024-10-15 06:23 UTC, Perbudag commented on .vs/sachkov-tech/v17/DocumentLayout.json
> +  "Version": 1,
Удалю

2024-10-15 06:39 UTC, Perbudag commented on backend/src/Files/SachkovTech.Files.Contracts/Dtos/GetLinkFileResult.cs
> +    public record GetLinkFileResult(FilePath FilePath, string Link);
Думаю все модели Result нужно перенести в application слой, потому, что они не используются вне модуля Files.

2024-10-15 11:36 UTC, KirillSachkov approved these changes

2024-10-15 17:37 UTC, merged