Malykhin/dev 8
KirillSachkov/sachkov-tech pull request #7
Opened 2024-10-02 19:54 UTC by superHatural

2024-10-02 20:05 UTC, superHatural commented
прошу посмотреть ModulesRepository, можно ли так удалять issue

2024-10-03 07:48 UTC, KirillSachkov requested changes

2024-10-03 07:48 UTC, KirillSachkov commented on .idea/.gitignore
![image](https://github.com/user-attachments/assets/da6675a2-1dbf-444c-bab3-6cd9c8025b23)
Этих файлов не должно быть в пулреквесте, .idea папки не должно быть, либо надо поднатроить .gitignore, либо что-то исправить в папках

2024-10-03 07:48 UTC, KirillSachkov commented on backend/src/SachkovTech.Application/IssueManagement/Commands/DeleteIssue/ForceDeleteIssue/ForceDeleteIssueHandler.cs
> +                return result.Error;
Удаление нужно делать не так. Мы делаем удаление через агрегат - модуль. То есть у модуля внутри делаем метод для удаления, удаляем из коллекции _issues задачу и потом просто сохраняем агрегат в базу данных с помощью savechanges

2024-10-03 07:48 UTC, KirillSachkov commented on backend/src/SachkovTech.Application/IssueManagement/Commands/DeleteIssue/SoftDeleteIssue/SoftDeleteIssueHandler.cs
> +        issueResult.Delete();
Нужно удалять задачу через модуль, внутри модуля нужно сделать метод, которые у issue вызывает delete. Метод delete у issue сделать internal, чтобы только модуль мог его вызывать. Потом просто сохранять изменения в бд

2024-10-03 07:48 UTC, KirillSachkov commented on backend/src/SachkovTech.Application/IssueManagement/Commands/UpdateIssueMainInfo/UpdateIssueMainInfoHandler.cs
> +            return updateResult.Error.ToErrorList();
Обновление нужно делать тоже через модуль. Сделать метод UpdateMainInfo internal и вызывать его через модуль

2024-10-03 07:48 UTC, KirillSachkov commented on backend/src/SachkovTech.Infrastructure/Repositories/ModulesRepository.cs
> +
В репозитории не должно быть бизнес логики, взя бизнес логика в доменной модели

2024-10-03 07:48 UTC, KirillSachkov commented on backend/src/SachkovTech.Infrastructure/Repositories/ModulesRepository.cs
> +
Репозиторий нужен исключительно для сохранения данных и для получения данных

2024-10-04 07:57 UTC, KirillSachkov approved these changes

2024-10-04 07:58 UTC, merged